# Numpy Broadcasting 練習
- 参考: https://numpy.org/doc/stable/user/basics.broadcasting.html

In [1]:
import numpy as np

In [3]:
# shape が同じ場合要素ごとに同じ演算を適用する
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 5.0])
a * b

array([ 2.,  4., 15.])

In [4]:
# @演算子は例外
a @ b

np.float64(21.0)

In [5]:
# broadcast の例
b = 2.0
a * b

array([2., 4., 6.])

## General broadcasting rules

2個のnumpy arrayに演算を行うとき， Numpyはそれらの形状 (shape) を比較して，

1. それらが等しい，または
2. そのうちのひとつが1

のとき計算できる．それらが満たされない場合は `ValueError` が投げられる．

In [6]:
# 計算できる例
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])

In [7]:
a.shape

(4, 3)

In [8]:
b.shape

(3,)

In [9]:
# 片方の次元が足りないとき，前方に1の形状をもつ次元を足して計算される
# (4, 3) + (3,) -> (4, 3) + (1, 3) --> (4, 3)
# (1, 3) に変換された b は 行方向に同じ配列がコピーされる (参考ページ Figure. 2)
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [10]:
# 同じ結果が得られる演算
# None は 1 の形状をもつ次元を追加する
print(b[None, :].shape)
a + b[None, :]

(1, 3)


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [11]:
# 計算できない例 (参考URL, Figure 3)
# (4, 3) + (1, 4) と解釈される→計算できない
b = np.array([1.0, 2.0, 3.0, 4.0])
print(a.shape, b.shape)
a + b

(4, 3) (4,)


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [17]:
# 参考URL, Figure 4 の例
# (4,) + (3,) -> 計算できない
# np.newaxis を加えて (4, 1) + (3,) -> (4, 1) + (1, 3) --> (4, 3)
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [18]:
a.shape

(4,)

In [19]:
b.shape

(3,)

In [20]:
a[:, np.newaxis].shape

(4, 1)

In [16]:
a[:, None].shape

(4, 1)

In [21]:
N = 10000
M = 5000
a = np.random.randn(N)
b = np.random.randn(M)

In [29]:
import time

In [30]:
# a, b を使って Figure 4 と同じような演算をしてみる
# broadcast を使わない書き方（めちゃ遅い）
t0 = time.time()
c = np.zeros((N, M))
for i in range(N):
    for j in range(M):
        c[i, j] = a[i] + b[j]
t1 = time.time()
print(t1 - t0)

7.2049641609191895


In [32]:
# broadcast を使う書き方（めっぽう速い）
t0 = time.time()
c2 = a[:, None] + b
t1 = time.time()
print(t1 - t0)

0.06542110443115234


In [26]:
c[:5, :5]

array([[-1.19088703, -0.45151388,  0.86075422,  2.43865881,  0.59205539],
       [-2.27923273, -1.53985959, -0.22759149,  1.35031311, -0.49629031],
       [-2.38685837, -1.64748522, -0.33521712,  1.24268747, -0.60391595],
       [-0.45687291,  0.28250023,  1.59476833,  3.17267293,  1.32606951],
       [-2.23683886, -1.49746571, -0.18519761,  1.39270699, -0.45389644]])

In [27]:
c2[:5, :5]

array([[-1.19088703, -0.45151388,  0.86075422,  2.43865881,  0.59205539],
       [-2.27923273, -1.53985959, -0.22759149,  1.35031311, -0.49629031],
       [-2.38685837, -1.64748522, -0.33521712,  1.24268747, -0.60391595],
       [-0.45687291,  0.28250023,  1.59476833,  3.17267293,  1.32606951],
       [-2.23683886, -1.49746571, -0.18519761,  1.39270699, -0.45389644]])